# Weight traffic splitting
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: accounts-service
  namespace: netcore-istio
spec:
  hosts:
    - accounts-service
  http:
  - route:
    - destination:
        host: accounts-service
        subset: v1
      weight: 70
    - destination:
        host: accounts-service
        subset: v2
      weight: 30
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: accounts-service
  namespace: netcore-istio
spec:
  host: accounts-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
# ---
# Request traffic splitting (enable this or weight traffic splitting)
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: accounts-service
#   namespace: netcore-istio
# spec:
#   hosts:
#     - accounts-service
#   http:
#   - match:
#     - headers:
#         user-country:
#           exact: denmark
#     route:
#     - destination:
#         host: accounts-service
#         subset: v2
#   - route:
#     - destination:
#         host: accounts-service
#         subset: v1