apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-sa
  namespace: netcore-linkerd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: netcore-linkerd
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/default-inbound-policy: all-authenticated
  labels:
    name: gateway-service
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
      version: v1
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/default-inbound-policy: all-authenticated
      labels:
        app: gateway-service
        version: v1
    spec:
      serviceAccountName: gateway-service-sa
      containers:
      - name: gateway-service
        image: gateway-service
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"    
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /swagger/index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "60"]
      - name: curl
        image: curlimages/curl 
        command: [ "sleep", "10000" ]
