{
 "title": "Unified service monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Main stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "milicores" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{ id!~\"/kube.*\", image!=\"\",container_name!=\"POD\",container!=\"POD\", pod=~\"gateway-service.*\", kubernetes_io_hostname=~\"minikube\"}[1m])) by (container_name, namespace, pod_name, pod)) * 1024",
     "legendFormat": "pod: {{ pod_name }}{{ pod }} | {{ container_name }}{{ contain}}"
    }
   ]
  },
  {
   "title": "Containers Memory usage (1m avg)",
   "type": "graph",
   "description": "Include container to see proxy and service",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!~\"/kube.*\", image!=\"\",container_name!=\"POD\",container!=\"POD\", pod=~\"gateway-service.*\",kubernetes_io_hostname=~\"minikube\"}) by (container_name, namespace, pod_name, pod)",
     "legendFormat": "pod: {{ pod_name }}{{ pod }} | {{ container_name }}{{ namespace}}"
    }
   ]
  },
  {
   "title": "Average CPU consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "milicores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{ id!~\"/kube.*\", image!=\"\",container_name!=\"POD\",container!=\"POD\", pod=~\"gateway-service.*\", kubernetes_io_hostname=~\"minikube\"}[1m])) by (container_name, pod_name)) * 1024"
    }
   ]
  },
  {
   "title": "Average memory consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!~\"/kube.*\", image!=\"\",container_name!=\"POD\",container!=\"POD\", pod=~\"gateway-service.*\",kubernetes_io_hostname=~\"minikube\"}) by (container_name, pod_name)"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"netcore-linkerd\", deployment=\"gateway-service\", direction=\"inbound\"}[5m])) by (le, deployment))"
    }
   ]
  },
  {
   "title": "Average pods count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"netcore-linkerd\", deployment=\"gateway-service\"})"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"gateway-service\",namespace=\"netcore-linkerd\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "sum(irate(request_total{deployment=\"gateway-service\",namespace=\"netcore-linkerd\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)"
    }
   ]
  },
  {
   "title": "P99 LATENCY",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"netcore-linkerd\", deployment=\"gateway-service\", direction=\"inbound\"}[5m])) by (le, deployment))"
    }
   ]
  },
  {
   "title": "POD COUNT",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=\"netcore-linkerd\", deployment=\"gateway-service\"})",
     "legendFormat": "sum(up{namespace=\"netcore-linkerd\", deployment=\"gateway-service\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"minikube\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"minikube\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"minikube\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"minikube\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"minikube\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"minikube\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"minikube\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"minikube\"})"
    }
   ]
  },
  { "title": "Unused", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$0.0356 / vCPU hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{ image!=\"\",container_name!=\"POD\",container!=\"POD\", pod=~\"gateway-service.*\", kubernetes_io_hostname=~\"minikube\"}[$__range])) by (pod, namespace)) / 3600 * 0.0356"
    }
   ]
  },
  {
   "title": "CPU usage seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{ image!=\"\",container_name!=\"POD\",container!=\"POD\", pod=~\"gateway-service.*\", kubernetes_io_hostname=~\"minikube\"}) "
    }
   ]
  },
  {
   "title": "Memory usage bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id!~\"/kube.*\", namespace=\"netcore-linkerd\", container=\"gateway-service\"}) / 1024 / 1024 / 1024 * 0.0039380"
    }
   ]
  },
  {
   "title": "AVG LATENCY OVER PERIOD ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"netcore-linkerd\", deployment=\"gateway-service\", direction=\"inbound\"}[5m])) by (le, deployment))[$__range:])"
    }
   ]
  }
 ]
}