apiVersion: v1
kind: ServiceAccount
metadata:
  name: netcore-accounts-service-sa
  namespace: netcore-istio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-accounts-service
  namespace: netcore-istio
  labels:
    name: netcore-accounts-service
    app: accounts-service
    version: v1
spec:
  selector:
    matchLabels:
      app: accounts-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts-service
        version: v1
    spec:
      serviceAccountName: netcore-accounts-service-sa
      containers:
      - name: accounts-service
        image: netcore-accounts-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"    
        ports:
        - containerPort: 80
        imagePullPolicy: Never