prometheus:
  url: http://prometheus.istio-system
  port: 9090

# In prometheus: istio_requests_total
# In custom metrics API: istio_requests_per_second
# http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1 

rules:
  default: false
  custom:
    - seriesQuery: 'istio_request_duration_milliseconds_bucket{namespace!="",pod!=""}'
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)_bucket$
        as: "avg_latency_over_30s"
      metricsQuery: avg_over_time(histogram_quantile(0.99, sum(irate(<<.Series>>{<<.LabelMatchers>>, namespace="netcore-istio", app="gateway-service"}[5m])) by (le, <<.GroupBy>>))[30s:])
        
    - seriesQuery: 'istio_requests_total{namespace!="",pod!=""}'
      resources:
        template: <<.Resource>>
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(irate(<<.Series>>{<<.LabelMatchers>>, destination_app="validation-service"}[5m])) by (<<.GroupBy>>)'